# Generated by Django 3.1.2 on 2020-11-01 11:26

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20201101_1625'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 11, 1, 11, 26, 4, 918572, tzinfo=utc)),
        ),
    ]
